# supabase/config.toml

# This is the main configuration file for your Supabase project.
# It's used to configure your local development environment and to apply settings when you deploy.

project_id = "1rfp-app" # You can find this in your Supabase project's URL

[api]
  port = 54321
  schemas = ["public", "storage", "graphql"]
  max_rows = 1000

[db]
  port = 54322
  major_version = 15

[studio]
  port = 54323

# This section configures the authentication settings for your project.
[auth]
  enabled = true
  site_url = "http://localhost:5173"
  additional_redirect_urls = []
  jwt_expiry = 3600
  enable_refresh_token_rotation = true
  refresh_token_reuse_interval = 10
  
  [auth.email]
    enable_signup = true
    double_confirm_changes = true
    enable_confirmations = true

# This is the corrected and merged configuration for your Edge Function.
[functions.grant-alert-sender]
  verify_jwt = false
  import_map = "./functions/grant-alert-sender/deno.json"
  entrypoint = "./functions/grant-alert-sender/index.ts"