# Netlify build settings - run from within fundspace-app directory
[build]
  command = "npm install && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["@google/generative-ai", "rss-parser", "@supabase/supabase-js"]
  node_bundler = "esbuild"

# Preserving your scheduled functions
[functions."fetch-and-cache-news"]
  schedule = "0 * * * *"

[functions."cleanup-old-news"]
  schedule = "0 0 * * *"

# SPA redirect for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Preserving your headers configuration
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, OPTIONS"