# Netlify build settings for your React app
[build]
  # CORRECTED: Since the build starts in 1rfp-app, we just need to run npm install.
  command = "npm install && npm run build"
  # CORRECTED: The publish directory is relative to the build's base directory.
  publish = "dist"

# Main functions configuration
[functions]
  # CORRECTED: The functions directory is also relative to the base directory.
  directory = "netlify/functions"
  external_node_modules = ["axios", "jsdom", "rss-parser", "@supabase/supabase-js"]
  node_bundler = "esbuild"

# Preserving your scheduled functions
[functions."fetch-and-cache-news"]
  schedule = "0 * * * *"

[functions."cleanup-old-news"]
  schedule = "0 0 * * *"

# Preserving your headers configuration
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, OPTIONS"