[build]
  command = "npm install && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["axios", "jsdom", "rss-parser", "@supabase/supabase-js"]
  node_bundler = "esbuild"

# THIS IS THE NEW, CRUCIAL PART
# This targets our specific function and forces files to be included.
[functions."process-grant-submission-background"]
  included_files = ["node_modules/@sparticuz/chromium/**"]

# Preserving your scheduled functions
[functions."fetch-and-cache-news"]
  schedule = "0 * * * *"

[functions."cleanup-old-news"]
  schedule = "0 0 * * *"

# Preserving your headers configuration
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, OPTIONS"