# Netlify build settings for your React app
[build]
  command = "npm install && npm run build"
  publish = "dist"

# Main functions configuration
[functions]
  directory = "netlify/functions"
  # ADDED @sparticuz/chromium HERE
  external_node_modules = ["axios", "jsdom", "rss-parser", "@supabase/supabase-js", "@sparticuz/chromium"]
  node_bundler = "esbuild"

# Preserving your scheduled functions
[functions."fetch-and-cache-news"]
  schedule = "0 * * * *"

[functions."cleanup-old-news"]
  schedule = "0 0 * * *"

# Preserving your headers configuration
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, OPTIONS"