# This configuration assumes it is run from the root of your repository.
[build]
  # 1. Go into the app folder, 2. install dependencies, 3. run the build script
  command = "cd 1rfp-app && npm install && npm run build"
  # The location of the final built site, relative to the repository root
  publish = "1rfp-app/dist"

[functions]
  # The location of your bundled functions, relative to the repository root
  directory = "1rfp-app/netlify/functions-dist"

# --- The rest of your settings remain the same ---

[functions."fetch-and-cache-news"]
  schedule = "0 * * * *"

[functions."cleanup-old-news"]
  schedule = "0 0 * * *"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, OPTIONS"