# Correct Netlify build settings
[build]
  command = "npm run build"
  publish = "dist"

# Functions configuration
[functions]
  directory = "netlify/functions"
  external_node_modules = ["axios", "jsdom", "rss-parser", "@supabase/supabase-js"]
  node_bundler = "esbuild"

# Add this block to explicitly configure the dev server
[dev]
  functions = "netlify/functions"

# Disable the problematic Neon database extension
[extensions]
  [extensions.neon]
    disabled = true

# Schedule the background function to run once every hour
[functions.fetch-and-cache-news]
  schedule = "0 * * * *"

# Schedule the cleanup function to run once a day
[functions.cleanup-old-news]
  schedule = "0 0 * * *"

# CORS headers for functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, OPTIONS"