[build]
  command = "npm run build"
  publish = "dist"

[functions]
  # This now points to the output directory where netlify-lambda builds the functions.
  directory = "netlify/functions-dist"

# We no longer need external_node_modules or included_files because
# the build:functions script bundles everything together for us.

# Preserving your scheduled functions
[functions."fetch-and-cache-news"]
  schedule = "0 * * * *"

[functions."cleanup-old-news"]
  schedule = "0 0 * * *"

# Preserving your headers configuration
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, OPTIONS"