[build]
  # We specify the full path for the command from the repo root
  command = "cd 1rfp-app && npm install && npm run build"
  # We specify the full path to the final built site
  publish = "1rfp-app/dist"

[functions]
  # We specify the full path to the bundled functions output
  directory = "1rfp-app/netlify/functions-dist"

# Preserving your scheduled functions
[functions."fetch-and-cache-news"]
  schedule = "0 * * * *"

[functions."cleanup-old-news"]
  schedule = "0 0 * * *"

# Preserving your headers configuration
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, OPTIONS"