# Netlify build settings for your React app
[build]
  # This command navigates into your app folder, installs dependencies, and builds it
  command = "cd 1rfp-app && npm install && npm run build"
  # This tells Netlify where the final built site is located
  publish = "1rfp-app/dist"

# Main functions configuration
[functions]
  # CORRECTED PATH: Points to the functions directory inside your 1rfp-app
  directory = "1rfp-app/netlify/functions"
  # Preserving your existing settings
  external_node_modules = ["axios", "jsdom", "rss-parser", "@supabase/supabase-js"]
  node_bundler = "esbuild"

# Development server settings
[dev]
  # CORRECTED PATH: For running locally with the Netlify CLI
  functions = "1rfp-app/netlify/functions"

# Preserving your scheduled functions
[functions."fetch-and-cache-news"]
  schedule = "0 * * * *"

[functions."cleanup-old-news"]
  schedule = "0 0 * * *"

# Preserving your headers configuration
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, OPTIONS"