# Netlify build settings
[build]
  # Tell Netlify the root of your app is here
  base = "1rfp-app"
  # The build command, Netlify runs "npm install" automatically
  command = "npm run build"
  # The final built site to publish
  publish = "1rfp-app/dist"

# Functions configuration
[functions]
  # Where the bundled functions will be placed by netlify-lambda
  directory = "1rfp-app/netlify/functions-dist"

# Preserving your scheduled functions
[functions."fetch-and-cache-news"]
  schedule = "0 * * * *"

[functions."cleanup-old-news"]
  schedule = "0 0 * * *"

# Preserving your headers configuration
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, OPTIONS"